import { Router, type IRouter } from "express";
import healthRouter from "./health";
import twinsRouter from "./twins";
import sleepRouter from "./sleep";
import feedingRouter from "./feeding";
import diapersRouter from "./diapers";
import routinesRouter from "./routines";
import videosRouter from "./videos";
import milestonesRouter from "./milestones";
import dashboardRouter from "./dashboard";
import onboardingRouter from "./onboarding";
import feedbackRouter from "./feedback";
import adminRouter from "./admin";
import adminRetentionRouter from "./admin-retention";
import pollsRouter from "./polls";
import storageRouter from "./storage";
import twinAiRouter from "./twin-ai";
import appUpdatesRouter from "./app-updates";
import usersRouter from "./users";
import statsRouter from "./stats";
import pushRouter from "./push";
import notificationsSchedulerRouter from "./notifications-scheduler";
import heartbeatRouter from "./heartbeat";
import clientErrorsRouter from "./client-errors";
import caregiversRouter from "./caregivers";
import communityRouter from "./community";
import planRouter from "./plan";

const router: IRouter = Router();

router.use(healthRouter);
router.use(twinsRouter);
router.use(sleepRouter);
router.use(feedingRouter);
router.use(diapersRouter);
router.use(routinesRouter);
router.use(videosRouter);
router.use(milestonesRouter);
router.use(dashboardRouter);
router.use(onboardingRouter);
router.use(feedbackRouter);
router.use(adminRouter);
router.use(adminRetentionRouter);
router.use(pollsRouter);
router.use(storageRouter);
router.use(twinAiRouter);
router.use(appUpdatesRouter);
router.use(usersRouter);
router.use(statsRouter);
router.use(pushRouter);
router.use(notificationsSchedulerRouter);
router.use(heartbeatRouter);
router.use(clientErrorsRouter);
router.use(caregiversRouter);
router.use(communityRouter);
router.use(planRouter);

export default router;
